function(enable_lto target)
  if(CMAKE_INTERPROCEDURAL_OPTIMIZATION)
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
    message(STATUS "🔧\tEnabled LTO for target ${target}")
  endif()
endfunction()
