name: clang-format

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '.clang-format'
      - 'cmake/Tooling.cmake'
      - '.github/workflows/clang-format.yml'

  pull_request:
    branches: [ master ]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '.clang-format'
      - 'cmake/Tooling.cmake'
      - '.github/workflows/clang-format.yml'

  workflow_dispatch:

jobs:
  format-check:
    name: Check clang-format
    runs-on: ubuntu-latest
    env:
      CMAKE_PRESET_NAME: gcc-Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-clang-format-${{ hashFiles('.github/workflows/clang-format.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-clang-format-

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ^3.28.0
          ninjaVersion: ^1.11.0

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install -y g++ gcc clang-format --no-install-recommends

      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build/
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure with CMake Preset
        run: cmake --preset $CMAKE_PRESET_NAME -DENABLE_CLANG_FORMAT=ON

      - name: Run clang-format
        run: cmake --build --preset $CMAKE_PRESET_NAME --target format-check
