name: clang-format

on:
  push:
    branches:
      - master
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '.clang-format'
      - '.github/workflows/clang-format.yml'
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '.clang-format'
      - '.github/workflows/clang-format.yml'

jobs:
  format-check:
    name: Check clang-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt update && sudo apt install -y clang-format

      - name: Run clang-format check
        run: |
          FILES=$(find . \( -name '*.cpp' -o -name '*.hpp' \) -not -path "./build/*")
          clang-format --dry-run --Werror $FILES
