name: Deploy Docs

permissions:
  contents: write

on:
  push:
    branches: [master]
    paths:
      - 'docs/Doxyfile.in'
      - 'include/**/*.hpp'
      - 'src/**/*.cpp'
      - '.github/workflows/docs.yml'
      - 'docs/mainpage.md'

jobs:
  generate-and-deploy:
    name: Build and Deploy Doxygen Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake + Doxygen dependencies
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz cmake ninja-build g++ gcc

      - name: Configure project with CMake Preset
        run: cmake --preset gcc-RelWithDebInfo -DBUILD_DOCS=ON

      - name: Generate Doxygen documentation
        run: cmake --build --preset gcc-RelWithDebInfo --target docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/gcc-RelWithDebInfo/docs/html
          publish_branch: gh-pages
          force_orphan: true
